name: flutter_echarts
description: A Flutter widget to use Echarts in a reactive way which builds awesome data visualization charts. Features are Reactive Updating, Two Way Communication, Configurable Extensions.
version: 1.1.0
author: LIN Chen <entronad@gmail.com>
homepage: https://github.com/entronad/flutter_echarts

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.17

dev_dependencies:
  flutter_test:
    sdk: flutter
