name: flutter_echarts
description: A data visualization charts library, based on Apache ECharts, able to build advanced charts like WebGL 3D, GIS map, etc.
version: 2.3.0
homepage: https://github.com/entronad/flutter_echarts

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
