name: flutter_echarts
description: A charts chart data visualization library, based on Echarts, with the capability to build WebGL 3D charts, GIS maps and other complex charts.
version: 1.1.0
author: LIN Chen <entronad@gmail.com>
homepage: https://github.com/entronad/flutter_echarts

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.17

dev_dependencies:
  flutter_test:
    sdk: flutter
